apiVersion: apps/v1 
kind: Deployment
metadata: 
  name: inference-deployment
  labels: 
    app: pede
  labels: 
    purpose: test-device-plugin 
spec: 
  replicas: 1
  selector: 
       matchLabels: 
           app: pede
  template: 
    metadata: 
      labels: 
        app: pede
      annotations: 
        k8s.v1.cni.cncf.io/networks: '[
                { "name" : "macvlan-conf-roce0" },
                { "name" : "macvlan-conf-roce1" },
                { "name" : "macvlan-conf-roce2" },
                { "name" : "macvlan-conf-roce3" }]'
    spec: 
      # modify replicas according to your case 
      containers: 
      - name: pede-test 
        image: 18823821553/graph-jupyter:inferencetest4
        command: ["/bin/bash", "-c", "./build/Multithreading/service/RestApi"] 
        securityContext: 
          privileged: true 
        resources:
          limits: 
            m2000.graphcore.ai/ipu: 1 # requesting an IPU 
        ports:
        - containerPort: 1984
        
          
---
apiVersion: v1
kind: Service
metadata:
  name: inference-service
spec:
  type: NodePort
  selector:
    app: pede
  ports:
    - protocol: TCP
      port: 80
      targetPort: 1984
      nodePort: 30080
